#!/bin/sh
exec 2>&1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

LAST=0
test -x /etc/runit/reboot && LAST=6

echo 'Waiting for services to stop...'
sv -w196 force-stop /service/*
sv exit /service/*

# run all one-time tasks from .d/
/bin/ls -1 /etc/runit/3.d/ |while read filename; do "/etc/runit/3.d/$filename" ; done

#
